In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
a=np.array([1,2,3,4,5])

In [6]:
print(a)

[1 2 3 4 5]


In [7]:
a=np.array([[2,3,4,56,5],[1,2,3,4,5]])
print(a)

[[ 2  3  4 56  5]
 [ 1  2  3  4  5]]


In [10]:
# min dimension
a=np.array([2,3,4,56,5],ndmin=5)

In [11]:
print(a)

[[[[[ 2  3  4 56  5]]]]]


In [12]:
#dtype parameter
a=np.array([1,2,3,4,5],dtype=complex)

In [13]:
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
